# configs/training_config.yaml
# Environment settings
env_name: BaseHumanoid4Ages
task: walk
mode: default
dataset_type: real
ref_motion: datasets/humanoids/real/mocap_motions/walking/walking_0.npz

# Training settings
total_steps: 10000000
steps_per_update: 2048
hidden_dims: [256, 256]
lr: 0.0003
gamma: 0.99
gae_lambda: 0.95
clip_ratio: 0.2
update_epochs: 10
mini_batch_size: 64
w_pose: 0.7
w_vel: 0.3

# Logging and saving
log_interval: 1
save_interval: 10
eval_interval: 10
render_interval: 20
output_dir: results
seed: 0
